name: CI/CD - BuildOnly

on:
    workflow_dispatch: {}
jobs:
    #Build Step
    buildProject:
        name: BuildWebGL
        runs-on: ubuntu-latest
        steps:
            #Repo Checkout
            - uses: actions/checkout@v4
            #Library Cache
            - uses: actions/cache@v4
              with:
                path: BalanceITUnityGame/Library
                key: Library-2023.2.20f1-${{  matrix.target-platform  }}
            #Builder Step
            - uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                with:
                targetPlatform: ${{  matrix.target-platform  }}
                projectPath: BalanceITUnityGame
                unityVersion: 2023.2.20f1
                buildName: BalanceITUnityGameBuild
            #Artifactupload
            - uses: actions/upload-artifact@v4
              with:
                name: ${{  matrix.target-platform  }}
                path: build/${{  matrix.target-platform  }}
        strategy:
            matrix:
                target-platform: 
                    - WebGL