name: CI/CD - TestOnly

on:
    workflow_dispatch: {}
jobs:
    # Testrunner Step
    testProject:
        name: Testrun Ubuntu
        runs-on: ubuntu-latest
        steps:
            #Repo Checkout
            - name: Checkout Repo
              uses: actions/checkout@v4
            #Tests Runnen mit GameCI
            - name: Run ${{  matrix.testMode }}
              id: testrun
              uses: game-ci/unity-test-runner@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                projectPath: BalanceITUnityGame
                githubToken: ${{ secrets.GITHUB_TOKEN }}
                testMode: ${{ matrix.testMode  }}
                artifactsPath: ${{  matrix.testMode  }}-artifacts
            #TestResults uploaden
            - name: Upload Test Result
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: Test results for ${{  matrix.testMode  }}
                path: ${{ matrix.testMode  }}-artifacts
        strategy:
            matrix:
                testMode:
                    - PlayMode
                    - EditMode