name: MPU-Script Test

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
      - 'features'
    paths:
      - 'MpuScript/Scripts/**'
  pull_request:
    branches:
      - 'main'
      - 'features'
    paths:
      - 'MpuScript/Scripts/**'

jobs:
  # Test MPU-Script C++
  testScript:
    name: Test-C++-Script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi

    - name: Set up PlatformIO
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: pip install platformio

    - name: Run Unit Tests
      run: |
        cd MpuScript/Tests
        platformio test -e native -v