name: CI - New Standalone Test

on:
    push:
        paths:
            - 'BalanceITUnityGame/Assets/**'
            - 'BalanceITUnityGame/Packages/**'
            - 'BalanceITUnityGame/ProjectSettings/**'
    workflow_dispatch: {}
jobs:
    #Test1
    Test1:
        name: Test1
        runs-on: ubuntu-latest
        steps:
            - run: ls
            - run: ls ${{ github.workspace }}
            - run: ls BalanceIT
    #Test2
    Test2:
        name: Test2
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: ls
            - name: test2 
              run: ls ${{ github.workspace }}
    # Testrunner Step
    testrunner:
        name: Testrun
        runs-on: ubuntu-latest
        steps:
            #Repo Checkout
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}
                path: BalanceITUnityGame

            #StandaloneTest Runnen mit GameCI
            - name: Run StandaloneTest
              id: standalone
              uses: game-ci/unity-test-runner@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                projectPath: BalanceITUnityGame
                githubToken: ${{ secrets.CIGITHUB_TOKEN }}
                testmode: standalone
                artifactsPath: standalone-artifacts
            #TestResults uploaden
            - name: Upload Test Result
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: Test results for StandaloneTest
                path: standalone-artifacts
    # Build Step
    buildProject:
        name: ${{ matrix.target-platform  }}
        runs-on: ${{  matrix.os  }}
        needs: testrunner
        if: success()
        steps:
            #Repo Checkout
            - uses: actions/checkout@v4
            #Library Cache
            - uses: actions/cache@v4
              with:
                path: BalanceITUnityGame/Library
                key: Library-${{  matrix.unity-version  }}-${{  matrix.target-platform  }}
            #Builder Step
            - uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                with:
                targetPlatform: ${{  matrix.target-platform  }}
                projectPath: BalanceITUnityGame
                unityVersion: ${{  matrix.unity-version  }}
                buildName: BalanceITUnityGameBuild
            #Artifactupload
            - uses: actions/upload-artifact@v4
              with:
                name: ${{  matrix.target-platform  }}
                path: build/${{  matrix.target-platform  }}
        strategy:
            matrix:
                unity-version:
                    - 2023.2.20f1
                    - auto
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      target-platform: StandaloneLinux64
                    - os: windows-latest
                      target-platform: StandaloneWindows64