name: CI - New Standalone Test

on:
    workflow_dispatch:

jobs:
    buildForLinux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                with:
                targetPlatform: StandaloneLinux64
                projectPath: BalanceITUnityGame
                unityVersion: 2023.2.20f1
                buildName: BalanceItGame
            - uses: actions/upload-artifact@v4
              with:
                name: StandAloneLinux64
                path: build/StandAloneLinux64