# This is a basic workflow to help you get started with Actions

name: Unity CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Installiere Unity, spezifische Version (hier 2023.2.20f1).
      - name: Set up Unity
        uses: game-ci/unity-installer@v3
        with:
          version: 2023.2.20f1

      # Aktivierung der Unity Lizenz.
      - name: Activate Unity license
        uses: game-ci/unity-activate@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  # Stelle sicher, dass du die Unity-Lizenz im GitHub Secrets hinterlegt hast.

          # Führe den Build durch (Windows, MacOS, WebGL etc.).
      - name: Build project
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: WebGL  # Beispiel für WebGL. Ändere dies je nach Zielplattform.

      # (Optional) Teste dein Unity-Projekt.
      - name: Test project
        run: |
          ./Unity/Editor/Unity -runTests -testPlatform PlayMode
          cat test-results.xml

      # Deaktiviere die Unity-Lizenz am Ende des Builds.
      - name: Deactivate Unity license
        uses: game-ci/unity-return-license@v3
